# .streamlit/secrets.toml
[email]
sender_email = "shazyblue1921@outlook.com"
password = "sherazkhan123"

[receiver]
receiver_emails = ["waqar.wahab412@gmail.com", "shazyblue1921@gmail.com"]

[scraper]
api_key = "83b5f03c34f9a50d4e6ec8c81cebdef0"